# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: YiSen's Blog
subtitle: "YiSen's Blog"
description: "我叫罗亦森，2020年6月毕业于中山大学南方学院，从事web开发已有4年。这是我掌握的[技能](/skill/)。
\n  
\n Email: 1402175410@qq.com"
keywords: YiSen's Blog
author: YiSen
language: zh-CN
timezone: ""

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://luoyisen.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: cactus
theme_config:
  # Customize the logo (i.e., the cactus) in the header.
  # Options:
  #   - enabled: whether to show (true) or hide (false) the logo.
  #   - width: width of the logo in pixel units
  #   - height: height of the logo in pixel units
  #   - url: where the logo can be found
  #   - gravatar: whether to use your Gravatar as the logo
  #   - grayout: whether to enable a hover effect on the logo
  logo:
    enabled: true
    width: 200
    height: 200
    url: /images/logo2.png
    gravatar: false
    grayout: false

  projects_url: /projects/

  # Color scheme
  colorscheme: custom

  # The color scheme that should be used to highlight codeblocks.
  # See source/css/_highlight for a list of all available color schemes.
  highlight: school-book

  # Customize the overview with displaying a tagcloud on the index page.
  tags_overview: false

  # Customize the overview with the most recent blog posts on the index page.
  # Options:
  #   - show_all_posts: whether to show all available posts.
  #   - post_count: whether to show only the x most recent posts.
  #   - sort_updated: sort posts by last modification date instead of creation date.
  posts_overview:
    show_all_posts: false
    post_count: 5
    sort_updated: false

  # Navigation
  nav:
    home: /
    articles: /archives/
    skill: /skill/
    tag: /tags/
    category: /categories/
    search: /search/

  # Social media links
  social_links:
    - 
      icon: github
      link: https://github.com/meiguiyisenluo
    - 
      icon: twitter
      link: https://twitter.com/javascript67335
    -
      icon: mail
      label: 1402175410@qq.com
      link: mailto:1402175410@qq.com
    -
      icon: gitter
      label: gitee
      link: https://gitee.com/luoyisen
    -
      icon: teamspeak
      label: xitujuejin
      link: https://juejin.cn/user/2322582188592296

  # Copyright years
  copyright:
    start_year: 2016
    end_year: 2023

  # Maximal width of the page in rem units.
  page_width: 40

  disqus:
    enabled: true
    shortname: yisen-1

  # Reward
  donate: true
  reward_comment: 如果您读文章后有收获，可以打赏我喝咖啡哦～
  wechatpay: /images/wechat.png
  # alipay: /images/alipay.png

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ""